// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: membership.proto

#ifndef PROTOBUF_INCLUDED_membership_2eproto
#define PROTOBUF_INCLUDED_membership_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_membership_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_membership_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_membership_2eproto();
namespace membership {
class reply_membership;
class reply_membershipDefaultTypeInternal;
extern reply_membershipDefaultTypeInternal _reply_membership_default_instance_;
class request_membership;
class request_membershipDefaultTypeInternal;
extern request_membershipDefaultTypeInternal _request_membership_default_instance_;
}  // namespace membership
namespace google {
namespace protobuf {
template<> ::membership::reply_membership* Arena::CreateMaybeMessage<::membership::reply_membership>(Arena*);
template<> ::membership::request_membership* Arena::CreateMaybeMessage<::membership::request_membership>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace membership {

// ===================================================================

class request_membership final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:membership.request_membership) */ {
 public:
  request_membership();
  virtual ~request_membership();

  request_membership(const request_membership& from);

  inline request_membership& operator=(const request_membership& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  request_membership(request_membership&& from) noexcept
    : request_membership() {
    *this = ::std::move(from);
  }

  inline request_membership& operator=(request_membership&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const request_membership& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const request_membership* internal_default_instance() {
    return reinterpret_cast<const request_membership*>(
               &_request_membership_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(request_membership* other);
  friend void swap(request_membership& a, request_membership& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline request_membership* New() const final {
    return CreateMaybeMessage<request_membership>(nullptr);
  }

  request_membership* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<request_membership>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const request_membership& from);
  void MergeFrom(const request_membership& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(request_membership* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // int32 read_only = 2;
  void clear_read_only();
  static const int kReadOnlyFieldNumber = 2;
  ::google::protobuf::int32 read_only() const;
  void set_read_only(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:membership.request_membership)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int32 read_only_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_membership_2eproto;
};
// -------------------------------------------------------------------

class reply_membership final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:membership.reply_membership) */ {
 public:
  reply_membership();
  virtual ~reply_membership();

  reply_membership(const reply_membership& from);

  inline reply_membership& operator=(const reply_membership& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  reply_membership(reply_membership&& from) noexcept
    : reply_membership() {
    *this = ::std::move(from);
  }

  inline reply_membership& operator=(reply_membership&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const reply_membership& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const reply_membership* internal_default_instance() {
    return reinterpret_cast<const reply_membership*>(
               &_reply_membership_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(reply_membership* other);
  friend void swap(reply_membership& a, reply_membership& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline reply_membership* New() const final {
    return CreateMaybeMessage<reply_membership>(nullptr);
  }

  reply_membership* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<reply_membership>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const reply_membership& from);
  void MergeFrom(const reply_membership& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(reply_membership* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 1;
  void clear_message();
  static const int kMessageFieldNumber = 1;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:membership.reply_membership)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_membership_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// request_membership

// string name = 1;
inline void request_membership::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& request_membership::name() const {
  // @@protoc_insertion_point(field_get:membership.request_membership.name)
  return name_.GetNoArena();
}
inline void request_membership::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:membership.request_membership.name)
}
#if LANG_CXX11
inline void request_membership::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:membership.request_membership.name)
}
#endif
inline void request_membership::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:membership.request_membership.name)
}
inline void request_membership::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:membership.request_membership.name)
}
inline ::std::string* request_membership::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:membership.request_membership.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* request_membership::release_name() {
  // @@protoc_insertion_point(field_release:membership.request_membership.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void request_membership::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:membership.request_membership.name)
}

// int32 read_only = 2;
inline void request_membership::clear_read_only() {
  read_only_ = 0;
}
inline ::google::protobuf::int32 request_membership::read_only() const {
  // @@protoc_insertion_point(field_get:membership.request_membership.read_only)
  return read_only_;
}
inline void request_membership::set_read_only(::google::protobuf::int32 value) {
  
  read_only_ = value;
  // @@protoc_insertion_point(field_set:membership.request_membership.read_only)
}

// -------------------------------------------------------------------

// reply_membership

// string message = 1;
inline void reply_membership::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& reply_membership::message() const {
  // @@protoc_insertion_point(field_get:membership.reply_membership.message)
  return message_.GetNoArena();
}
inline void reply_membership::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:membership.reply_membership.message)
}
#if LANG_CXX11
inline void reply_membership::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:membership.reply_membership.message)
}
#endif
inline void reply_membership::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:membership.reply_membership.message)
}
inline void reply_membership::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:membership.reply_membership.message)
}
inline ::std::string* reply_membership::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:membership.reply_membership.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* reply_membership::release_message() {
  // @@protoc_insertion_point(field_release:membership.reply_membership.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void reply_membership::set_allocated_message(::std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:membership.reply_membership.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace membership

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_membership_2eproto
