// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: membership.proto

#include "membership.pb.h"
#include "membership.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace membership {

static const char* MemRequest_method_names[] = {
  "/membership.MemRequest/SayHello",
};

std::unique_ptr< MemRequest::Stub> MemRequest::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MemRequest::Stub> stub(new MemRequest::Stub(channel));
  return stub;
}

MemRequest::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(MemRequest_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MemRequest::Stub::SayHello(::grpc::ClientContext* context, const ::membership::request_membership& request, ::membership::reply_membership* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void MemRequest::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::membership::request_membership* request, ::membership::reply_membership* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void MemRequest::Stub::experimental_async::SayHello(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::membership::reply_membership* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::membership::reply_membership>* MemRequest::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::membership::request_membership& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::membership::reply_membership>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::membership::reply_membership>* MemRequest::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::membership::request_membership& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::membership::reply_membership>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

MemRequest::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MemRequest_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MemRequest::Service, ::membership::request_membership, ::membership::reply_membership>(
          std::mem_fn(&MemRequest::Service::SayHello), this)));
}

MemRequest::Service::~Service() {
}

::grpc::Status MemRequest::Service::SayHello(::grpc::ServerContext* context, const ::membership::request_membership* request, ::membership::reply_membership* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace membership

