// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: membership.proto

#include "membership.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace membership {
class request_membershipDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<request_membership> _instance;
} _request_membership_default_instance_;
class reply_membershipDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<reply_membership> _instance;
} _reply_membership_default_instance_;
}  // namespace membership
static void InitDefaultsrequest_membership_membership_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::membership::_request_membership_default_instance_;
    new (ptr) ::membership::request_membership();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::membership::request_membership::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_request_membership_membership_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsrequest_membership_membership_2eproto}, {}};

static void InitDefaultsreply_membership_membership_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::membership::_reply_membership_default_instance_;
    new (ptr) ::membership::reply_membership();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::membership::reply_membership::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_reply_membership_membership_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsreply_membership_membership_2eproto}, {}};

void InitDefaults_membership_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_request_membership_membership_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_reply_membership_membership_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_membership_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_membership_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_membership_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_membership_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::membership::request_membership, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::membership::request_membership, name_),
  PROTOBUF_FIELD_OFFSET(::membership::request_membership, read_only_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::membership::reply_membership, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::membership::reply_membership, message_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::membership::request_membership)},
  { 7, -1, sizeof(::membership::reply_membership)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::membership::_request_membership_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::membership::_reply_membership_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_membership_2eproto = {
  {}, AddDescriptors_membership_2eproto, "membership.proto", schemas,
  file_default_instances, TableStruct_membership_2eproto::offsets,
  file_level_metadata_membership_2eproto, 2, file_level_enum_descriptors_membership_2eproto, file_level_service_descriptors_membership_2eproto,
};

const char descriptor_table_protodef_membership_2eproto[] =
  "\n\020membership.proto\022\nmembership\"5\n\022reques"
  "t_membership\022\014\n\004name\030\001 \001(\t\022\021\n\tread_only\030"
  "\002 \001(\005\"#\n\020reply_membership\022\017\n\007message\030\001 \001"
  "(\t2X\n\nMemRequest\022J\n\010SayHello\022\036.membershi"
  "p.request_membership\032\034.membership.reply_"
  "membership\"\000B6\n\033io.grpc.examples.members"
  "hipB\017MembershipProtoP\001\242\002\003MEMb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_membership_2eproto = {
  false, InitDefaults_membership_2eproto, 
  descriptor_table_protodef_membership_2eproto,
  "membership.proto", &assign_descriptors_table_membership_2eproto, 276,
};

void AddDescriptors_membership_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_membership_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_membership_2eproto = []() { AddDescriptors_membership_2eproto(); return true; }();
namespace membership {

// ===================================================================

void request_membership::InitAsDefaultInstance() {
}
class request_membership::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int request_membership::kNameFieldNumber;
const int request_membership::kReadOnlyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

request_membership::request_membership()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:membership.request_membership)
}
request_membership::request_membership(const request_membership& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  read_only_ = from.read_only_;
  // @@protoc_insertion_point(copy_constructor:membership.request_membership)
}

void request_membership::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_request_membership_membership_2eproto.base);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  read_only_ = 0;
}

request_membership::~request_membership() {
  // @@protoc_insertion_point(destructor:membership.request_membership)
  SharedDtor();
}

void request_membership::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void request_membership::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const request_membership& request_membership::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_request_membership_membership_2eproto.base);
  return *internal_default_instance();
}


void request_membership::Clear() {
// @@protoc_insertion_point(message_clear_start:membership.request_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  read_only_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* request_membership::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<request_membership*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("membership.request_membership.name");
        object = msg->mutable_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int32 read_only = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_read_only(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool request_membership::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:membership.request_membership)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "membership.request_membership.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 read_only = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &read_only_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:membership.request_membership)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:membership.request_membership)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void request_membership::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:membership.request_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "membership.request_membership.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // int32 read_only = 2;
  if (this->read_only() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->read_only(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:membership.request_membership)
}

::google::protobuf::uint8* request_membership::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:membership.request_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "membership.request_membership.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // int32 read_only = 2;
  if (this->read_only() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->read_only(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:membership.request_membership)
  return target;
}

size_t request_membership::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:membership.request_membership)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 read_only = 2;
  if (this->read_only() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->read_only());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void request_membership::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:membership.request_membership)
  GOOGLE_DCHECK_NE(&from, this);
  const request_membership* source =
      ::google::protobuf::DynamicCastToGenerated<request_membership>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:membership.request_membership)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:membership.request_membership)
    MergeFrom(*source);
  }
}

void request_membership::MergeFrom(const request_membership& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:membership.request_membership)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.read_only() != 0) {
    set_read_only(from.read_only());
  }
}

void request_membership::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:membership.request_membership)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void request_membership::CopyFrom(const request_membership& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:membership.request_membership)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool request_membership::IsInitialized() const {
  return true;
}

void request_membership::Swap(request_membership* other) {
  if (other == this) return;
  InternalSwap(other);
}
void request_membership::InternalSwap(request_membership* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(read_only_, other->read_only_);
}

::google::protobuf::Metadata request_membership::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_membership_2eproto);
  return ::file_level_metadata_membership_2eproto[kIndexInFileMessages];
}


// ===================================================================

void reply_membership::InitAsDefaultInstance() {
}
class reply_membership::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int reply_membership::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

reply_membership::reply_membership()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:membership.reply_membership)
}
reply_membership::reply_membership(const reply_membership& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  // @@protoc_insertion_point(copy_constructor:membership.reply_membership)
}

void reply_membership::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_reply_membership_membership_2eproto.base);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

reply_membership::~reply_membership() {
  // @@protoc_insertion_point(destructor:membership.reply_membership)
  SharedDtor();
}

void reply_membership::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void reply_membership::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const reply_membership& reply_membership::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_reply_membership_membership_2eproto.base);
  return *internal_default_instance();
}


void reply_membership::Clear() {
// @@protoc_insertion_point(message_clear_start:membership.reply_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* reply_membership::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<reply_membership*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string message = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("membership.reply_membership.message");
        object = msg->mutable_message();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool reply_membership::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:membership.reply_membership)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string message = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "membership.reply_membership.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:membership.reply_membership)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:membership.reply_membership)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void reply_membership::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:membership.reply_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "membership.reply_membership.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->message(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:membership.reply_membership)
}

::google::protobuf::uint8* reply_membership::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:membership.reply_membership)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "membership.reply_membership.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->message(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:membership.reply_membership)
  return target;
}

size_t reply_membership::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:membership.reply_membership)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void reply_membership::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:membership.reply_membership)
  GOOGLE_DCHECK_NE(&from, this);
  const reply_membership* source =
      ::google::protobuf::DynamicCastToGenerated<reply_membership>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:membership.reply_membership)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:membership.reply_membership)
    MergeFrom(*source);
  }
}

void reply_membership::MergeFrom(const reply_membership& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:membership.reply_membership)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void reply_membership::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:membership.reply_membership)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void reply_membership::CopyFrom(const reply_membership& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:membership.reply_membership)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool reply_membership::IsInitialized() const {
  return true;
}

void reply_membership::Swap(reply_membership* other) {
  if (other == this) return;
  InternalSwap(other);
}
void reply_membership::InternalSwap(reply_membership* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata reply_membership::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_membership_2eproto);
  return ::file_level_metadata_membership_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace membership
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::membership::request_membership* Arena::CreateMaybeMessage< ::membership::request_membership >(Arena* arena) {
  return Arena::CreateInternal< ::membership::request_membership >(arena);
}
template<> PROTOBUF_NOINLINE ::membership::reply_membership* Arena::CreateMaybeMessage< ::membership::reply_membership >(Arena* arena) {
  return Arena::CreateInternal< ::membership::reply_membership >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
